<a href="https://colab.research.google.com/github/camilamurillo1/Valores-Nulos/blob/main/NoNulos_Detalle_precios_y_productos_fabricados_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df= pd.read_csv("Detalle precios y productos fabricados 2022.csv")
df

,CVE_DOC,FECHA_DOC,NOMBRE,NOMBRE.1,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",$434.48,$52.80,$52.80,$434.48,$52.80,$381.68,$381.68
1,F37036,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT","$1,264.05",$327.18,$327.18,"$1,264.05",$327.18,$936.87,$936.87
2,F37041,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,$551.61,$177.68,$177.68,"$3,861.29","$1,243.73",$373.94,"$2,617.56"
3,F37042,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,$140,$38.96,$38.96,$140,$38.96,$101.04,$101.04
4,F37043,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,$172.41,$101.71,$101.71,$344.83,$203.42,$70.71,$141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,23/12/2022 00:00,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",$712,$102.31,$102.31,"$4,272",$613.88,$609.69,"$3,658.12"
1422,F39834,23/12/2022 00:00,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",$718.60,$104.69,$104.69,"$4,311.60",$628.12,$613.91,"$3,683.48"
1423,F39835,23/12/2022 00:00,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP","$2,182.35",$0,$596.55,"$6,547.05","$1,789.64","$1,585.80","$4,757.41"
1424,F39837,23/12/2022 00:00,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT","$5,909.84","$1,884.35","$1,884.35","$5,909.84","$1,884.35","$4,025.49","$4,025.49"
1425,F39838,23/12/2022 00:00,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,"$1,406",$0,$80.66,"$14,060",$806.55,"$1,325.34","$13,253.45"

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

CVE_DOC                      0
FECHA_DOC                    0
NOMBRE                       2
NOMBRE.1                     0
CANT                         0
CVE_ART                      0
DESCR                        0
PRECIO_UNITARIO              0
COSTO_UNITARIO               0
COSTO_UNITARIO_CALCULADO     0
SUBTOTAL_PARTIDA             0
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

In [ ]:
df["NOMBRE"] =df["NOMBRE"].fillna("Sin registro") 
df

,CVE_DOC,FECHA_DOC,NOMBRE,NOMBRE.1,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",$434.48,$52.80,$52.80,$434.48,$52.80,$381.68,$381.68
1,F37036,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT","$1,264.05",$327.18,$327.18,"$1,264.05",$327.18,$936.87,$936.87
2,F37041,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,$551.61,$177.68,$177.68,"$3,861.29","$1,243.73",$373.94,"$2,617.56"
3,F37042,05/01/2022 00:00,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,$140,$38.96,$38.96,$140,$38.96,$101.04,$101.04
4,F37043,05/01/2022 00:00,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,$172.41,$101.71,$101.71,$344.83,$203.42,$70.71,$141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,23/12/2022 00:00,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",$712,$102.31,$102.31,"$4,272",$613.88,$609.69,"$3,658.12"
1422,F39834,23/12/2022 00:00,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",$718.60,$104.69,$104.69,"$4,311.60",$628.12,$613.91,"$3,683.48"
1423,F39835,23/12/2022 00:00,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP","$2,182.35",$0,$596.55,"$6,547.05","$1,789.64","$1,585.80","$4,757.41"
1424,F39837,23/12/2022 00:00,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT","$5,909.84","$1,884.35","$1,884.35","$5,909.84","$1,884.35","$4,025.49","$4,025.49"
1425,F39838,23/12/2022 00:00,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,"$1,406",$0,$80.66,"$14,060",$806.55,"$1,325.34","$13,253.45"

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

CVE_DOC                      0
FECHA_DOC                    0
NOMBRE                       0
NOMBRE.1                     0
CANT                         0
CVE_ART                      0
DESCR                        0
PRECIO_UNITARIO              0
COSTO_UNITARIO               0
COSTO_UNITARIO_CALCULADO     0
SUBTOTAL_PARTIDA             0
COSTO_TOTAL_CALCULADO        0
MARGEN_UNITARIO_CALCULADO    0
MARGEN_TOTAL_CALCULADO       0
dtype: int64

In [ ]:
df.to_csv("Precios y productos2022.csv")
from google.colab import files   
files.download("Precios y productos2022.csv")