<a href="https://colab.research.google.com/github/camilamurillo1/Valores-Nulos/blob/main/Nulos_Gastos20_23_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*2020*

In [ ]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Gastos y costos 20-23.xlsx')

In [ ]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3347 entries, 0 to 3346
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CALOR Y CONTROL S.A DE C.V  3344 non-null   object
 1   Unnamed: 1                  3154 non-null   object
 2   Unnamed: 2                  3343 non-null   object
 3   Unnamed: 3                  3343 non-null   object
 4   Unnamed: 4                  3343 non-null   object
 5   Unnamed: 5                  3343 non-null   object
 6   Unnamed: 6                  841 non-null    object
 7   Unnamed: 7                  3343 non-null   object
 8   Unnamed: 8                  2952 non-null   object
 9   Unnamed: 9                  3309 non-null   object
 10  Unnamed: 10                 3075 non-null   object
 11  Unnamed: 11                 3343 non-null   object
 12  Unnamed: 12                 3343 non-null   object
 13  GASTO                       3346 non-null   object
 14  10418041.599137934          3346 non-null   object
 15  Unnamed: 15                 3342 non-null   object
 16  Unnamed: 16                 3343 non-null   object
 17  Unnamed: 17                 22 non-null     object
 18  Unnamed: 18                 3343 non-null   object
dtypes: object(19)
memory usage: 496.9+ KB

In [ ]:
#Eliminar primera fila o filas innecesarias
df= pd.read_excel('Gastos y costos 20-23.xlsx', skiprows=[0,1,2,3,4])
df

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,NaN,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,NaN,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,NaN,0.00
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,NaN,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,NaN,0.00
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,NaN,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,2020-12-01,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,G VTA,32011 MAGNA,1.0,129.79,20.21,0.0,0.0,150.00,150.00,I,Vigente,NaN,0.00
3338,2020-12-01,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,G VTA,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1.0,2284.80,365.57,0.0,0.0,2650.37,2650.37,I,Vigente,NaN,0.00
3339,2020-12-01,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,G VTA,REF VICTORIA GROSELLA 3 LT PET NR,1.0,163.79,26.21,0.0,0.0,190.00,190.00,I,Vigente,NaN,0.00
3340,2020-12-01,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,G FINA,COMISIONES E INTERESES,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,NaN,0.00
3341,2020-12-01,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,G VTA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1.0,14889.29,0.00,0.0,0.0,14889.29,14889.29,I,Vigente,NaN,0.00

In [ ]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df["FOLIO"] =df["FOLIO"].fillna("Sin registro")

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [ ]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df["GASTO"]= df["GASTO"].fillna(0)

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO             0
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [ ]:
df["TC"]= df["TC"].fillna(0)

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO             0
DESCRIPCION       0
TC                0
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [ ]:
df["IMPORTE"]= df["IMPORTE"].fillna(0)

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO             0
DESCRIPCION       0
TC                0
IMPORTE           0
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [ ]:
df["IVA"] = df["IVA"].fillna(df["IMPORTE"] * 0.16)

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO             0
DESCRIPCION       0
TC                0
IMPORTE           0
IVA               0
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [ ]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df["TIPO"] =df["TIPO"].fillna("Sin registro")

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

FECHA             0
FOLIO             0
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO             0
DESCRIPCION       0
TC                0
IMPORTE           0
IVA               0
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              0
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [ ]:
df["POLIZA"] =df["POLIZA"].fillna("Sin registro")

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
GASTO          0
DESCRIPCION    0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           0
STATUS         0
POLIZA         0
Columna1       0
dtype: int64

#*2021*

In [ ]:
#Carga desde un archivo .xlsx sin indice
df2= pd.read_excel('2021.xlsx')

In [ ]:
#Eliminar primera fila o filas innecesarias
df2= pd.read_excel('2021.xlsx', skiprows=[0,1,2,])
df2

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,DESCRIPCION,MP,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA
0,2021-01-01,0001010100750847116902,71B4C8B9-8DAA-47CC-AD47-9DD90AA5AF6B,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,0
1,2021-01-01,0001010100752163714102,B8AEDE83-CC76-404C-A611-6B5A87BA561F,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1.0,345.00,55.20,0.0,0.0,400.20,400.20,I,Vigente,0
2,2021-01-01,19788,19B9B2C2-DF58-E24D-B43A-3FC4D5A929E7,ESI9612311E7,"ELECTRONICOS Y SIMILARES, S.A. DE C.V.",COMPRAS,MOTO E7 PLUS AZUL 64GB 4RAM,PUE,1.0,3447.41,551.59,0.0,0.0,3999.00,3999.00,I,Vigente,0
3,2021-01-01,211781,EAB26414-DD9A-4E8F-9F5C-05FE24D98E48,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 6/36 de 03/12/2...,PPD,1.0,5551.38,888.22,0.0,0.0,6439.60,6439.60,I,Vigente,0
4,2021-01-01,211782,C16F79B5-FB35-4BFC-AF84-708B24F500BB,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 6/36 de 03/12/2...,PPD,1.0,5551.98,888.32,0.0,0.0,6440.30,6440.30,I,Vigente,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3030,2021-12-01,127043,83F82167-0D14-144E-9D76-045C95F25DDD,PGM881128QIA,"PROMOCIONES GRAFICAS MEXICANAS, S.A. DE C.V.",PUBLICIDAD,Pago,NaN,1.0,0.00,0.00,0.0,0.0,0.00,0.00,P,Vigente,NaN
3031,2021-12-01,11740,B1C60AE0-02BC-4A33-9513-A280F72B5D06,SME0510105C7,SPECTRIS MEXICO S DE RL DE CV,COMPRAS,INSULATED T/C WIRE,PUE,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,NaN
3032,2021-12-01,1092957089,255F4A25-5753-4208-8F6B-0B59E5AE4741,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,1.0,22826.46,705.58,0.0,0.0,23532.04,23532.04,I,Vigente,NaN
3033,2021-12-01,747826,D8226E4F-9241-44C3-86A4-CDE9BC932528,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,NaN
3034,2021-12-01,1227374,41770F35-39EF-41A4-8DF4-EE9586CF4549,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,GASOLINA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,PUE,1.0,15656.15,0.00,0.0,0.0,15656.15,15656.15,I,Vigente,NaN

In [ ]:
valores_nulos=df.isnull().sum()
valores_nulos

In [ ]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df2["FOLIO"] =df2["FOLIO"].fillna("Sin registro")
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
df2["TIPO GASTO"]= df2["TIPO GASTO"].fillna(0)
#Se pone 0 en los faltante de tipo de cambio con la finalidad de no tener valores nulos en el data frame   
df2["TC"]= df2["TC"].fillna(0) 
df2["IMPORTE"]= df2["IMPORTE"].fillna(0) 
df2["IVA"] = df2["IVA"].fillna(df2["IMPORTE"] * 0.16)
df2["TIPO"] =df2["TIPO"].fillna("Sin registro")
df2["POLIZA"] =df2["POLIZA"].fillna("Sin registro")
df2["MP"] =df2["MP"].fillna("Sin registro")

In [ ]:
valores_nulos=df2.isnull().sum()
valores_nulos

FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
DESCRIPCION    0
MP             0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           0
STATUS         0
POLIZA         0
dtype: int64

#*2022*

In [ ]:
#Carga desde un archivo .xlsx sin indice
df3= pd.read_excel('2022.xlsx')

In [ ]:
#Eliminar primera fila o filas innecesarias
df3= pd.read_excel('2022.xlsx', skiprows=[0,1,2,])
df3

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2022-01-01,280108,9DA0E63F-1D47-441F-93D7-C2E05AE4D35E,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 18/36 de 03/12/...,PPD,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE02-ENE22
1,2022-01-01,280109,7E00E776-A839-4D57-B291-411109164B2F,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 18/36 de 03/12/...,PPD,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE03-ENE22
2,2022-01-01,007817297284,BB6585C1-3B54-4130-AFD0-1867C3764821,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,Servicios de Facturación,PUE,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
3,2022-01-01,5595,B5E4B4EB-6C2F-11EC-BB9D-00155D014009,ZEGC530520V4A,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
4,2022-01-01,5614,BB6756D1-6CCD-11EC-947D-00155D014407,ZEGC530520V4A,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2572,2022-12-01,863376,E90DA089-3C3B-45C8-A19C-B8810D222F60,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
2573,2022-12-01,1092957089,D720ED7C-F370-4236-B269-8873ABB78745,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,1.0,17310.30,516.32,0.0,0.0,NaN,17826.62,17826.62,I,Vigente,NaN
2574,2022-12-01,4,0AFD3EB5-F3DD-43EB-B9FA-79D793CFF417,AAE6411055P8,Aesa Articulos Electricos S.A de C.V,COMPRAS,Pago,NaN,NaN,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2575,2022-12-01,16,E3CA1DA8-581A-5844-80D2-CF0317B3BBEA,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2576,2022-12-01,17,17178BA2-9CCE-54F8-A4B8-3E5F98D4DB8E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN

In [ ]:
valores_nulos=df3.isnull().sum()
valores_nulos

Fecha             0
Folio             0
UUID              0
RFC               0
Proveedor         0
TIPO GASTO        0
Descripción       0
MP                0
TC                0
Importe           0
IVA               0
RET ISR           0
RET IVA           0
Otros          2577
TOTAL MX          0
TOTAL SAT         0
Tipo              0
Status            0
Poliza            0
dtype: int64

In [ ]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df3["Folio"] =df3["Folio"].fillna("Sin registro")
df3["MP"] =df3["MP"].fillna("Sin registro")
df3["TC"]= df3["TC"].fillna(0) 
df3["Poliza"] =df3["Poliza"].fillna("Sin registro")
df3["Otros"]= df3["Otros"].fillna(0)

In [ ]:
valores_nulos=df3.isnull().sum()
valores_nulos

Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     0
Descripción    0
MP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
Otros          0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

#*2023*

In [ ]:
#Carga desde un archivo .xlsx sin indice
df4= pd.read_excel('2023.xlsx')
#Eliminar primera fila o filas innecesarias
df4= pd.read_excel('2023.xlsx', skiprows=[0,1,2,])
df4

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,NaN,9807.07,9807.07,I,Vigente,PE03-ENE23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2023-02-01,882974,3E97C399-6747-4BCA-8436-ED4B0933DF33,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,3.0,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
393,2023-02-01,053560,B7132758-F800-4797-B1D6-CC61AFFEE444,BPU7901018D4,BEBIDAS PURIFICADAS,ALIMENTOS,Epura 20 Lts Policarbonato,PUE,1.0,1.0,220.00,0.00,0.0,0.0,NaN,220.00,220.00,I,Vigente,NaN
394,2023-02-01,1092957089,D1E2DC1E-9FFB-46C6-82E4-B350B83CB6F7,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,3.0,1.0,18071.52,682.40,0.0,0.0,NaN,18753.92,18753.92,I,Vigente,NaN
395,2023-02-01,1453820,6249FE27-6FA6-4EFB-910E-3CD67A0E29A1,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,GASOLINA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,PUE,5.0,1.0,14472.32,0.00,0.0,0.0,NaN,14472.32,14472.32,I,Vigente,NaN
396,2023-02-01,18,439A9230-277E-5563-818C-7630B0E8D706,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN

In [ ]:
valores_nulos=df4.isnull().sum()
valores_nulos

Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     8
Descripción    0
MP             0
FP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
Otros          0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

In [ ]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df4["Folio"] =df4["Folio"].fillna("Sin registro")
df4["MP"] =df4["MP"].fillna("Sin registro")
df4["Poliza"] =df4["Poliza"].fillna("Sin registro")
df4["Otros"]= df4["Otros"].fillna(0) 
df4["FP"]= df4["FP"].fillna(0)

In [ ]:
#Convertir archivo filtrado a CSV
df.to_csv("df.csv")

#descardar archivo filtrado en csv
from google.colab import files   
files.download("df.csv")

In [ ]:
#Convertir archivo filtrado a CSV
df2.to_csv("df2.csv")

#descardar archivo filtrado en csv
from google.colab import files   
files.download("df2.csv")

In [ ]:
#Convertir archivo filtrado a CSV
df3.to_csv("df3.csv")

#descardar archivo filtrado en csv
from google.colab import files   
files.download("df3.csv")

In [ ]:
#Convertir archivo filtrado a CSV
df4.to_csv("df4.csv")

#descardar archivo filtrado en csv
from google.colab import files   
files.download("df4.csv")